export const cardData = [
  {
    id: 1,
    title: "Modal 3",
    description: "Schedule a Test Drive",
    backgroundImg: "model-3.jpg",
    leftBtnText: "Custom order",
    RightBtnText: "Existing inventory",
  },
  {
    id: 2,
    title: "Modal Y",
    description: "Schedule a Test Drive",
    backgroundImg: "model-y.jpg",
    leftBtnText: "Custom order",
    RightBtnText: "Existing inventory",
  },
  {
    id: 3,
    title: "Modal S",
    description: "Schedule a Test Drive",
    backgroundImg: "model-s.jpg",
    leftBtnText: "Custom order",
    RightBtnText: "Existing inventory",
  },
  {
    id: 4,
    title: "Modal X",
    description: "Schedule a Test Drive",
    backgroundImg: "model-x.jpg",
    leftBtnText: "Custom order",
    RightBtnText: "Existing inventory",
  },
  {
    id: 5,
    title: "Solar Panels",
    description: "Lowest Cost Solar Panels in America",
    backgroundImg: "solar-panel.jpg",
    leftBtnText: "Order Now",
    RightBtnText: "Learn more",
  },
  {
    id: 6,
    title: "Solar Roof",
    description: "Produce Clean Energy From Your Roof",
    backgroundImg: "solar-roof.jpg",
    leftBtnText: "Order Now",
    RightBtnText: "Learn more",
  },
  {
    id: 7,
    title: "Accessories",
    description: "",
    backgroundImg: "accessories.jpg",
    leftBtnText: "Shop Now",
    RightBtnText: "Learn more",
  },
];
